name: Build project

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]

jobs:
    build:
        name: Build project
        runs-on: ubuntu-latest

        steps:
            - name: Check the code
              uses: actions/checkout@v4

            - name: Setup JDK
              uses: actions/setup-java@v4
              with:
                distribution: 'temurin'
                java-version: '17'
            
            - name: Create a dummy keystore file
              run: touch keystore.keystore

            - name: Setup Gradle
              uses: gradle/actions/setup-gradle@v4

            - name: Build the project
              run: ./gradlew build